"""add embedding and context to person_messages

Revision ID: 70a6bce71295
Revises: 05e1d458d146
Create Date: 2026-04-29 04:10:21.498905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '70a6bce71295'
down_revision: Union[str, Sequence[str], None] = '05e1d458d146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_messages', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('person_messages', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_messages', 'embedding')
    op.drop_column('person_messages', 'context')
    # ### end Alembic commands ###
